(load-file "~/xsrc/snippets/.emacs.d/dotemacs")
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(canlock-password "320a46eeec84e8e4e041534d821600d69eb36d15")
 '(dired-listing-switches "-aBhl --dired --group-directories-first --sort=extension")
 '(erc-log-channels-directory "~/x/log/erc")
 '(erc-nick "malc")
 '(ibuffer-default-sorting-mode 'mode-name)
 '(load-home-init-file t t)
 '(notmuch-saved-searches
   '((:name "inbox" :query "tag:inbox" :key "i")
     (:name "flagged" :query "tag:flagged" :key "f")
     (:name "sent" :query "tag:sent" :key "t")
     (:name "drafts" :query "tag:draft" :key "d")
     (:name "all mail" :query "*" :key "a")
     (:name "uread" :query "tag:unread")
     (:name "llpp" :query "llpp")
     (:name "unread" :query "tag:unread")))
 '(org-agenda-files '("~/x/org/agenda"))
 '(org-support-shift-select t)
 '(package-selected-packages
   '(helm-notmuch notmuch notmuch-bookmarks notmuch-labeler notmuch-maildir ivy monkeytype pinentry highlight-numbers lacarte xkcd tuareg helm-ls-git helm-git-grep helm-bbdb helm-ag))
 '(send-mail-function 'smtpmail-send-it))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Info-quoted ((t nil)))
 '(button ((t (:inherit (link)))))
 '(cursor ((t (:background "black"))))
 '(erc-current-nick-face ((t (:foreground "green4" :weight bold))))
 '(erc-keyword-face ((t (:foreground "blue1" :weight bold))))
 '(erc-timestamp-face ((t (:foreground "dark green" :weight bold))))
 '(escape-glyph ((t (:foreground "#0076c1"))))
 '(fixed-pitch ((t (:inherit (default)))))
 '(font-lock-builtin-face ((t (:weight bold))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-string-face)))))
 '(font-lock-comment-face ((t (:foreground "#204A87"))))
 '(font-lock-doc-face ((t (:foreground "#527c00"))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#00578E"))))
 '(font-lock-keyword-face ((t (:foreground "#A52A2A"))))
 '(font-lock-negation-char-face ((t (:foreground "#204A87"))))
 '(font-lock-preprocessor-face ((t (:foreground "#c80084"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#555753"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#888a85"))))
 '(font-lock-string-face ((t (:foreground "#0076c1"))))
 '(font-lock-type-face ((t (:foreground "#004d41"))))
 '(font-lock-variable-name-face ((t (:weight bold :foreground "#0076c1"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#CC0000"))))
 '(fringe ((t (:background "#DBDBDB"))))
 '(gnus-cite-5 ((t (:foreground "maroon"))))
 '(header-line ((t (:foreground "#555753" :background "#C3C7CF"))))
 '(helm-M-x-key ((t (:foreground "blue1"))))
 '(helm-bookmark-info ((t (:foreground "tomato3" :weight bold))))
 '(helm-locate-finish ((t (:foreground "black"))))
 '(highlight ((t (:foreground "#2E3436" :background "#FEFFBF"))))
 '(hl-line ((t (:background "black" :foreground "white"))))
 '(isearch ((t (:foreground "#FFFFFF" :background "#204A87"))))
 '(isearch-fail ((t (:foreground "#FFFFFF" :background "#CC0000"))))
 '(lazy-highlight ((t (:foreground "#555753" :background "#FEFFBF"))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#0066CC"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#c80084"))))
 '(match ((t (:foreground "#FFFFFF" :background "#00578E"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#0066CC"))))
 '(mode-line ((t (:height 0.9 :box (:line-width 1 :color nil :style nil)))))
 '(mode-line-buffer-id ((t (:height 0.9 :foreground "#2E3436"))))
 '(mode-line-emphasis ((t (:weight bold :background "grey70"))))
 '(mode-line-highlight ((t (:height 0.9 :foreground "#2E3436" :background "#FEFFBF"))))
 '(next-error ((t (:inherit (region)))))
 '(org-headline-done ((t nil)))
 '(query-replace ((t (:inherit (isearch)))))
 '(region ((t (:background "#FEFFBF"))))
 '(secondary-selection ((t (:background "#EDD400"))))
 '(sh-heredoc ((t (:foreground "dim gray"))))
 '(shadow ((t (:foreground "#555753"))))
 '(speed-type-correct ((t (:foreground "darkgreen"))))
 '(variable-pitch ((t (:inherit (default)))))
 '(whitespace-line ((t (:background "white" :foreground "black")))))
;;; Local Variables:
;;; End:
